FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
  gcc \
  && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x wait-for-db.py entrypoint.sh

ENV PORT=8000
EXPOSE $PORT

# Запуск через наш скрипт
ENTRYPOINT ["./entrypoint.sh"]